### ISSUE TITLE
error: no member named 'from_chars' in namespace 'std'

### ISSUE THREAD

**Issue by Martinfx** [ZathuraDbg/ZathuraDbg#91]
```
/home/maxfx/Documents/ZathuraDbg/src/app/windows/registerWindow.cpp:639:51: error: no member named 'from_chars' in namespace 'std'
  639 |                             auto [ptr, ec] = std::from_chars(value.data(), value.data() + value.size(), val);
      |                                              ~~~~~^
/home/maxfx/Documents/ZathuraDbg/src/app/windows/registerWindow.cpp:659:51: error: no member named 'from_chars' in namespace 'std'
  659 |                             auto [ptr, ec] = std::from_chars(value.data(), value.data() + value.size(), val);

```

FreeBSD clang version 18.1.5 (https://github.com/llvm/llvm-project.git llvmorg-18.1.5-0-g617a15a9eac9)
Target: x86_64-unknown-freebsd14.1
Thread model: posix
InstalledDir: /usr/bin

**Comment by mrexodia** [comment]
Probably missing `#include <charconv>`

**Comment by Martinfx** [comment]
> Probably missing `#include <charconv>`
is not in FreeBSD clang

**Comment by mrexodia** [comment]
Perhaps the project isn’t set to compile as c++17 then? It’s part of the c++ standard library, so it cannot really be “missing” (other than as a packaging bug)

**Comment by mrexodia** [comment]
Try to add `set(CXX_STANDARD_REQUIRED ON)` here https://github.com/ZathuraDbg/ZathuraDbg/blob/master/src/CMakeLists.txt#L4

I don’t think the project is meant to work on BSD though, but it might work 🤷‍♂️

**Comment by HACKE-RC** [comment]
Yeah, I haven't tested anything on BSD

**Comment by Martinfx** [comment]
from mark Millard FreeBSD
Lines 640 and 641, for example:

                            double val;
                            auto [ptr, ec] = std::from_chars(value.data(), value.data() + value.size(), val);


So: Not supported until libc++ from LLVM 20. 
FreeBSD's main [so: 15-CURRENT] just recently updated to LLVM 19. Note that the devel/llvm* ports/packages use the system libc++ . They do not provide their own libc++ . So it is going to be a while before a system libc++ is based on LLVM 20 or later in a releng/* (*.*-RELEASE) FreeBSD build.

**Comment by HACKE-RC** [comment]
Is there anything else that fails to compile on BSD? I can replace those with older C++ features together

**Comment by Martinfx** [comment]
> Is there anything else that fails to compile on BSD? I can replace those with older C++ features together

i have only this issue now.

**Comment by mrexodia** [comment]
If you start down this road you can keep going forever and you’ll end up supporting 10+ year old toolchains. The user should just install a reasonable version of libc++. `charconv` has been a header since c++17, which was released 7 years ago.

I did the same for x64dbg and it still supports Windows XP to this day, but eventually this becomes a very large maintenance burden.

**Comment by HACKE-RC** [comment]
I see, I misunderstood and thought that this person is on the latest libc++. @Martinfx you should update it nonetheless, since I plan to use the latest C++ features in all the future releases of ZathuraDbg.

**Comment by Martinfx** [comment]
> I see, I misunderstood and thought that this person is on the latest libc++. @Martinfx you should update it nonetheless, since I plan to use the latest C++ features in all the future releases of ZathuraDbg.

OK. i will use gcc13 and it is ok. what is -lunicorn ?

**Comment by HACKE-RC** [comment]
![Screenshot_20241111-071608](https://github.com/user-attachments/assets/6e764065-703f-4533-a905-c2f863fc98da)
A library on which ZathuraDbg depends on

**Comment by Martinfx** [comment]
Ok.thank you.
